version: '3'

services:

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8888:8888"

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: my_pass
      MYSQL_DATABASE: flask_db
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql_pass
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55