services:
  proxy:
    build:
      context: ./proxy
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    build:
      context: ./db
    environment:
     MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="${DB_ROOT_PASSWORD}" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    env_file:
      - path: ./.env