version: '3'

services:
  proxy:
    build:
      context: ./proxy
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /passwords/mysql-root-password.txt
    volumes:
      - ./passwords:/passwords
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /passwords/mysql-root-password.txt)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
